name: 🍏 iOS Builds
on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

# Global Settings
env:
  SCONSFLAGS: threads=no dev_build=yes debug_symbols=yes optimize=debug module_text_server_fb_enabled=yes

jobs:
  ios-template:
    runs-on: macos-latest
    timeout-minutes: 60
    name: Template (target=template_debug)
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Template (target=template_debug, v8)
            cache-name: ios-template-debug-v8
            target: template_debug
            cache-limit: 1

          - name: Template (target=template_debug, qjs_ng)
            cache-name: ios-template-debug-qjs-ng
            target: template_debug
            sconsflags: use_quickjs_ng=yes
            cache-limit: 1

#          - name: Template (target=template_debug, jsc)
#            cache-name: ios-template-jsc
#            target: template_debug
#            sconsflags: use_jsc=yes
#            cache-limit: 1

    steps:
      - name: Checkout Godot
        uses: actions/checkout@v4
        with:
          repository: godotengine/godot
          ref: ${{ inputs.version }}
          submodules: recursive

      - name: Checkout GodotJS
        uses: actions/checkout@v4
        with:
          path: ${{github.workspace}}/modules/GodotJS/
          lfs: true
          submodules: recursive

      - name: Restore Godot build cache
        uses: ./.github/actions/godot-cache-restore
        continue-on-error: true

      - name: Download deps artifact
        uses: actions/download-artifact@v4
        with:
          name: V8
          path: ${{github.workspace}}/modules/GodotJS/v8

      - name: Setup Python and SCons
        uses: ./.github/actions/godot-deps

      - name: Compilation (arm64)
        uses: ./.github/actions/godot-build
        with:
          sconsflags: ${{ env.SCONSFLAGS }}  ${{ matrix.sconsflags }}
          platform: ios
          target: ${{ matrix.target }}
          scons-cache-limit: ${{ matrix.cache-limit }}

      - name: Save Godot build cache
        uses: ./.github/actions/godot-cache-save
        with:
          cache-name: ${{ matrix.cache-name }}
        continue-on-error: true

      - name: Upload artifact
        uses: ./.github/actions/upload-artifact
        with:
          name: ${{ matrix.cache-name }}
