name: 🔗 GHA

on:
  push:
    branches:
      - "godot-4.6-debug-templates"

concurrency:
  group: ${{ github.workflow }}|${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  environment:
    name: 🌳 Set Environment
    uses: ./.github/workflows/misc_environment.yml

  web-build:
    name: 🌐 Web
    needs: [environment]
    uses: ./.github/workflows/build_web.yml
    with:
      version: "4.6"
      version_mm: "4.6"
      version_ref: 4.6-stable
      release: false

  macos-build:
    name: 🍎 macOS
    needs: [environment]
    uses: ./.github/workflows/build_macos.yml
    with:
      version: "4.6"
      version_mm: "4.6"
      version_ref: 4.6-stable
      release: false
